use sea_orm_migration::prelude::*;


/// The main function for the migration service, this allows the sea-orm-migration CLI to run the migrations.
/// This is autogenerated mostly by the sea-orm-migration CLI, and should not need to be modified.
#[tokio::main]
pub async fn main() {
    cli::run_cli(migration::Migrator).await;
}
